### ISSUE TITLE
six==1.4.1 into virtualenv installation error

### ISSUE THREAD

**Issue by thala7** [socrocket/core#2]
Hi,
In my project,I am working with **Soc rocket**.
I have an issue during soc rocket configuration and build environment.I require your assistance to solve it.
Thank you
with regards
Karthik

************************************************************************************************************************************
[karthik7@eduroam-pool12-1346 core]$ ./waf configure 
Setting top to                           : /home/karthik7/socrocket3/core 
Setting out to                           : /home/karthik7/socrocket3/core/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'python'            : /usr/bin/python 
Checking for waf version in 1.6.0-1.9.0  : ok 
Checking for python version              : (2, 7, 10, 'final', 0) 
python-config                            : /usr/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags' flags : yes 
Testing pyembed configuration                                      : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags   : yes 
Testing pyext configuration                                        : yes 

      To compile SoCRocket you need to have installed a basic Unix system.
      Atleast it needs to contain: 

        nm, git, patch, make, wget / curl, tar, ln, bash ans swig, python.

      Moreover you will need the development packages from readline:

        libreadline-dev

      Furthermore you need to provide cross compiler for sparc. If not provided
      we will try to fetch them from Gaisler (sparc-elf-gcc). But you will need 
      to provice a 32bit environment to execute the precompiled toolchain.

      For the ipython support blas and lapack needs to be installed.
    
Checking for program 'nm'                                          : /usr/bin/nm 
Checking for program 'git'                                         : /usr/bin/git 
Checking for program 'patch'                                       : /usr/bin/patch 
Checking for program 'make'                                        : /usr/bin/make 
Checking for program 'wget'                                        : /usr/bin/wget 
Checking for program 'tar'                                         : /usr/bin/tar 
Checking for program 'ln'                                          : /usr/bin/ln 
Checking for program 'bash'                                        : /usr/bin/bash 
Checking for linker flags -pthread                                 : yes 
Checking for compiler flags -pthread                               : yes 
Checking for compiler version                                      : ok - 5.3.1 
Determining gcc search path                                        : ok 
Checking for g++ optimization flags                                : yes 
Checking for gcc optimization flags                                : yes 
Checking for C compilation flags                                   : yes 
Checking for C compilation flags                                   : yes 
Checking for C++ compilation flags                                 : yes 
Checking for link flags                                            : yes 
Checking boost includes                                            : 1.57.0 
boost: static parameter is deprecated, use stlib instead.
Checking boost libs                                                : ok 
Checking for boost linkage                                         : ok 
Checking for host endianness                                       : little 
Checking for header cxxabi.h                                       : yes 
Checking for function abi::__cxa_demangle                          : yes 
Checking for static library elf                                    : not found 
Fetching libelf                                                    : Already done 
Extracting libelf                                                  : Already done 
Building libelf                                                    : Already done 
Checking for static library elf                                    : yes 
Checking for header libelf.h                                       : yes 
Checking for header gelf.h                                         : yes 
Checking for static library systemc                                : not found, compiling internal version. To use a system wide version use --with-systemc option 
Fetching systemc                                                   : Already done 
Extracting systemc                                                 : Already done 
Building systemc                                                   : Already done 
Checking for static library systemc                                : yes 
Checking for header systemc.h                                      : yes 
Checking for SystemC version                                       : yes 
Checking for SystemC Version 2.3.0+                                : yes 
Checking for header tlm.h                                          : yes 
Check for TLM version                                              : yes 
Checking for program 'cmake'                                       : not found 
Fetching cmake                                                     : Already done 
Extracting cmake                                                   : Already done 
Building cmake                                                     : Already done 
Checking for program 'cmake'                                       : /home/karthik7/socrocket3/core/build/.conf_check_deps/dist/cmake-2.8.12/bin/cmake 
Checking for program 'swig'                                        : /usr/bin/swig 
Checking for header greensocket/initiator/single_socket.h          : no 
Cloning greenlib                                                   : Already done 
Checking for header greenlib/gs_sc_api_detection.h                 : ok 
Checking for header greensocket/initiator/single_socket.h          : ok 
Checking for header greensocket/target/single_socket.h             : ok 
Checking for header greencontrol/config.h                          : ok 
Checking for header amba.h                                         : AMBAKit not found please give the location with --amba= 
Fetching amba_socket                                               : Already done 
Extracting amba_socket                                             : Already done 
Patching amba_socket with /home/karthik7/socrocket3/core/core/waf/ambakit-2015-10-16-rmeyer.patch : Failed, make sure patch /home/karthik7/socrocket3/core/core/waf/ambakit-2015-10-16-rmeyer.patch was already applied 
Checking for header amba.h                                                                        : ok 
Checking for AMBAKit Version > 1.0.5                                                              : ok 
Checking for program 'doxygen'                                                                    : /usr/bin/doxygen 
Checking for program 'swig'                                                                       : /usr/bin/swig 
Checking cpplint                                                                                  : ok 
Checking for program 'oclint'                                                                     : not found 
Fetching oclint                                                                                   : Already done 
Extracting oclint                                                                                 : Already done 
Checking for program 'oclint'                                                                     : /home/karthik7/socrocket3/core/build/.conf_check_deps/dist/oclint-0.7-x86_64-linux-ubuntu-12.04/bin/oclint 
Checking for 'gcc' (C compiler)                                                                   : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)                                                                 : /usr/bin/g++ 
Checking for program 'sparc-elf-gcc'                                                              : not found 
Fetching sparc-elf                                                                                : Already done 
Extracting sparc-elf                                                                              : Already done 
Checking for program 'sparc-elf-gcc'                                                              : /home/karthik7/socrocket3/core/build/.conf_check_deps/dist/sparc-elf-4.4.2/bin/sparc-elf-gcc 
Checking for program 'sparc-elf-g++'                                                              : /home/karthik7/socrocket3/core/build/.conf_check_deps/dist/sparc-elf-4.4.2/bin/sparc-elf-g++ 
Checking for C compilation flags                                                                  : yes 
Checking for link flags                                                                           : yes 
Checking for program 'virtualenv2'                                                                : not found 
Cloning virtualenv                                                                                : Already done 
Checking for program 'virtualenv.py'                                                              : /home/karthik7/socrocket3/core/build/.conf_check_deps/dist/virtualenv-trunk/virtualenv.py 
Create python virtualenv                                                                          : ok 
Checking for program 'python'                                                                     : /home/karthik7/socrocket3/core/build/.conf_check_venv/bin/python 
Checking for program 'pip'                                                                        : /home/karthik7/socrocket3/core/build/.conf_check_venv/bin/pip 
Install Pygments==1.6 into virtualenv                                                             : ok 
**Install six==1.4.1 into virtualenv**                                                                : **Command ['/home/karthik7/socrocket3/core/build/.conf_check_venv/bin/pip', 'install', 'six==1.4.1'] returned 1**

**Comment by bfarkas** [comment]
Have you tried running `pip install six==1.4.1` separately? Alternatively it would help to look into the `build/config.log` and see what exactly is the error. Maybe you can paste the last few lines of that file here?

**Comment by thala7** [comment]
Hi bfarkas,
Here is the config.log information for the above mentioned problem. I just over come this error by changing version number at **nano pysc/waf/shell.py.** However i am getting another error at **Install tables==3.1.1** . I am adding both config.log information below.
with regards 
Kathik

*******************************************************************************************************************************
**error install six==1.4.1(config.log)*************************
Install six==1.4.1 into virtualenv
['/home/karthik7/socrocket3/core/build/.conf_check_venv/bin/pip', 'install', 'six==1.4.1']
out: Collecting six==1.4.1
  Using cached six-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-N2U0d3/six/setup.py", line 29, in <module>
        classifiers=six_classifiers
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/karthik7/socrocket3/core/build/.conf_check_venv/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/karthik7/socrocket3/core/build/.conf_check_venv/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/home/karthik7/socrocket3/core/build/.conf_check_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/karthik7/socrocket3/core/build/.conf_check_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.4.1 (/home/karthik7/socrocket3/core/build/.conf_check_venv/lib/python2.7/site-packages), Requirement.parse('six>=1.6.0'))
    
    ----------------------------------------

err: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-N2U0d3/six/
********************************************************************************************************************************
*******************************************************************************************************************************

*********error Install tables==3.1.1(config.log)** 
Install tables==3.1.1 into virtualenv
['/home/karthik7/socrocket2/core/build/.conf_check_venv/bin/pip', 'install', 'tables==3.1.1']
out: Collecting tables==3.1.1
  Downloading tables-3.1.1.tar.gz (6.7MB)
    Complete output from command python setup.py egg_info:
    /tmp/H5closeZchzP7.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/H5closeZchzP7.c: In function ‘main’:
    /tmp/H5closeZchzP7.c:2:5: warning: implicit declaration of function ‘H5close’ [-Wimplicit-function-declaration]
         H5close();
         ^
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 2.7.10 (default, Jun 20 2016, 14:45:40)
    * Found numpy 1.9.1 package installed.
    * Found numexpr 2.4 package installed.
    * Found Cython 0.20.2 package installed.
    /usr/bin/ld: cannot find -lhdf5
    collect2: error: ld returned 1 exit status
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------

err: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ex6Jv4/tables/

**Comment by bfarkas** [comment]
Which Linux distribution are you using? You should be able to just install the hdf5 libraries devel headers from the package repository. On Ubuntu this would be `sudo apt-get install libhdf5-dev` on Red Had/Centos `yum install hdf5 hdf5-devel`. Then you probably need to set the `HDF5_DIR` environment variable. To do this directly inside the venv and install tables you can execute `source build/.conf_check_venv/bin/activate` followed by `HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/ pip install tables==3.1.1` (the exact path might vary depending on your setup)

**Comment by thala7** [comment]
Thank you very much bfrakas.Its working After installing the HDF5 library .And in my case with out setting the environment variable configuration succeeded .
BTW I am using Fedora 22 operating system. :)
